# Generated by Django 5.2.17 on 2026-09-22 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="شماره فاکتور",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("deposit", "بیعانه"), ("settlement", "تسویه نهایی")],
                        default="deposit",
                        max_length=20,
                        verbose_name="نوع پرداخت",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="مبلغ (تومان)")),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="بابت"
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        default="sandbox", max_length=40, verbose_name="درگاه"
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=120,
                        verbose_name="کد رهگیری درگاه",
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=60,
                        verbose_name="شماره پیگیری بانک",
                    ),
                ),
                (
                    "card_pan",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="شماره کارت"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پرداخت"),
                            ("paid", "پرداخت موفق"),
                            ("failed", "ناموفق"),
                            ("cancelled", "انصراف کاربر"),
                            ("refunded", "بازگشت وجه"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پرداخت"
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="پاسخ درگاه"
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="appointments.appointment",
                        verbose_name="نوبت",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="پرداخت\u200cکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت",
                "verbose_name_plural": "پرداخت\u200cها",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="payments_pa_status_21ed42_idx",
                    )
                ],
            },
        ),
    ]
