# Generated by Django 5.2.17 on 2026-09-22 23:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="تاریخ")),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="مناسبت"
                    ),
                ),
            ],
            options={
                "verbose_name": "روز تعطیل",
                "verbose_name_plural": "روزهای تعطیل",
                "ordering": ("date",),
            },
        ),
        migrations.CreateModel(
            name="WorkingHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "شنبه"),
                            (1, "یکشنبه"),
                            (2, "دوشنبه"),
                            (3, "سه\u200cشنبه"),
                            (4, "چهارشنبه"),
                            (5, "پنجشنبه"),
                            (6, "جمعه"),
                        ],
                        unique=True,
                        verbose_name="روز هفته",
                    ),
                ),
                ("is_open", models.BooleanField(default=True, verbose_name="باز است")),
                (
                    "open_time",
                    models.TimeField(
                        default=datetime.time(9, 0), verbose_name="ساعت شروع"
                    ),
                ),
                (
                    "close_time",
                    models.TimeField(
                        default=datetime.time(20, 0), verbose_name="ساعت پایان"
                    ),
                ),
                (
                    "slot_minutes",
                    models.PositiveSmallIntegerField(
                        default=60,
                        help_text="مثلاً ۶۰ یعنی نوبت\u200cها ساعت ۹:۰۰، ۱۰:۰۰ و ... باشند.",
                        verbose_name="فاصله\u200cی نوبت\u200cها (دقیقه)",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="چند خودرو را می\u200cتوانید هم\u200cزمان در یک بازه بپذیرید.",
                        verbose_name="ظرفیت هم\u200cزمان",
                    ),
                ),
            ],
            options={
                "verbose_name": "ساعت کاری",
                "verbose_name_plural": "ساعت\u200cهای کاری",
                "ordering": ("weekday",),
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True, max_length=10, unique=True, verbose_name="کد پیگیری"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, default="", max_length=11, verbose_name="شماره تماس"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="تاریخ به صورت شمسی از تقویم انتخاب می\u200cشود.",
                        verbose_name="تاریخ نوبت",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="ساعت شروع")),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="ساعت پایان"),
                ),
                (
                    "car_model",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="خودرو"
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="شماره پلاک"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="آسیب خودرو را شرح دهید: محل ضربه، میزان خرابی و خواسته\u200cی شما.",
                        verbose_name="توضیحات مشتری",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار تایید"),
                            ("confirmed", "تایید شده"),
                            ("in_progress", "در حال انجام"),
                            ("done", "انجام شده"),
                            ("cancelled", "لغو شده توسط مشتری"),
                            ("rejected", "رد شده توسط مغازه"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "staff_note",
                    models.TextField(
                        blank=True, default="", verbose_name="یادداشت مغازه"
                    ),
                ),
                (
                    "estimated_price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="برآورد هزینه (تومان)"
                    ),
                ),
                (
                    "deposit_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مبلغ بیعانه (تومان)"
                    ),
                ),
                (
                    "is_deposit_paid",
                    models.BooleanField(
                        default=False, verbose_name="بیعانه پرداخت شده"
                    ),
                ),
                (
                    "deposit_paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پرداخت بیعانه"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="services.service",
                        verbose_name="خدمت",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مشتری",
                    ),
                ),
            ],
            options={
                "verbose_name": "نوبت",
                "verbose_name_plural": "نوبت\u200cها",
                "ordering": ("-date", "-start_time"),
            },
        ),
        migrations.CreateModel(
            name="AppointmentPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="appointments/%Y/%m/", verbose_name="عکس خودرو"
                    ),
                ),
                (
                    "angle",
                    models.CharField(
                        choices=[
                            ("front", "جلوی خودرو"),
                            ("back", "عقب خودرو"),
                            ("left", "سمت چپ"),
                            ("right", "سمت راست"),
                            ("closeup", "نمای نزدیک آسیب"),
                            ("roof", "سقف / کاپوت"),
                            ("other", "سایر"),
                        ],
                        default="other",
                        max_length=10,
                        verbose_name="زاویه عکس",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="توضیح عکس"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="زمان بارگذاری"
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="appointments.appointment",
                        verbose_name="نوبت",
                    ),
                ),
            ],
            options={
                "verbose_name": "عکس نوبت",
                "verbose_name_plural": "عکس\u200cهای نوبت",
                "ordering": ("angle", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["date", "start_time"], name="appointment_date_85ff09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["status", "-date"], name="appointment_status_73815b_idx"
            ),
        ),
    ]
