# Generated by Django 5.2.17 on 2026-09-23 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(verbose_name="مبلغ بیعانه (تومان)"),
                ),
                (
                    "authority",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="کد Authority زرین\u200cپال",
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="کد پیگیری تراکنش"
                    ),
                ),
                (
                    "card_pan",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        verbose_name="شماره کارت پرداخت\u200cکننده",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پرداخت"),
                            ("success", "موفق"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پرداخت موفق"
                    ),
                ),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="bookings.appointment",
                        verbose_name="نوبت",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت",
                "verbose_name_plural": "پرداخت\u200cها",
                "ordering": ["-created_at"],
            },
        ),
    ]
