# Generated by Django 5.2.17 on 2026-09-20 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=60,
                        verbose_name="کلید سشن",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "سبد خرید",
                "verbose_name_plural": "سبدهای خرید",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ref_code",
                    models.CharField(
                        blank=True, max_length=20, unique=True, verbose_name="کد پیگیری"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="نام گیرنده"),
                ),
                ("phone", models.CharField(max_length=11, verbose_name="شماره تماس")),
                (
                    "province",
                    models.CharField(blank=True, max_length=60, verbose_name="استان"),
                ),
                ("city", models.CharField(max_length=60, verbose_name="شهر")),
                ("address", models.TextField(verbose_name="آدرس")),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=10, verbose_name="کد پستی"),
                ),
                ("note", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "items_price",
                    models.PositiveIntegerField(default=0, verbose_name="جمع کالاها"),
                ),
                (
                    "shipping_cost",
                    models.PositiveIntegerField(default=0, verbose_name="هزینه ارسال"),
                ),
                (
                    "total_price",
                    models.PositiveIntegerField(default=0, verbose_name="مبلغ نهایی"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پرداخت"),
                            ("paid", "پرداخت شده"),
                            ("processing", "در حال آماده\u200cسازی"),
                            ("shipped", "ارسال شده"),
                            ("delivered", "تحویل شده"),
                            ("canceled", "لغو شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ پرداخت"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارش\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_title",
                    models.CharField(max_length=200, verbose_name="نام محصول"),
                ),
                (
                    "variant_label",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="سایز و رنگ"
                    ),
                ),
                ("unit_price", models.PositiveIntegerField(verbose_name="قیمت واحد")),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(default=1, verbose_name="تعداد"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "قلم سفارش",
                "verbose_name_plural": "اقلام سفارش",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(default=1, verbose_name="تعداد"),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.cart",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.productvariant",
                        verbose_name="تنوع محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "قلم سبد خرید",
                "verbose_name_plural": "اقلام سبد خرید",
                "ordering": ["added_at"],
                "unique_together": {("cart", "variant")},
            },
        ),
    ]
