# Generated by Django 5.2.17 on 2026-09-29 10:40

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="نام برند"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="نام انگلیسی"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        help_text="در صورت خالی بودن از نام انگلیسی (یا فارسی) ساخته می\u200cشود.",
                        max_length=120,
                        unique=True,
                        verbose_name="نامک (آدرس)",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="تصویر مربعی با پس\u200cزمینه سفید یا شفاف، حداقل ۳۰۰×۳۰۰ پیکسل",
                        upload_to="brands/",
                        verbose_name="لوگو",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="کشور سازنده"
                    ),
                ),
                (
                    "description",
                    apps.core.fields.RichTextField(
                        blank=True, verbose_name="معرفی برند"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "برند",
                "verbose_name_plural": "برندها",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=120,
                        unique=True,
                        verbose_name="نامک (آدرس)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="categories/",
                        verbose_name="تصویر / آیکون",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="برای زیردسته، دسته اصلی را انتخاب کنید.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.category",
                        verbose_name="دسته والد",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام محصول")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=220,
                        unique=True,
                        verbose_name="نامک (آدرس)",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="کد محصول (SKU)"
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="توضیح کوتاه"
                    ),
                ),
                (
                    "description",
                    apps.core.fields.RichTextField(
                        blank=True, verbose_name="توضیحات کامل"
                    ),
                ),
                ("price", models.PositiveIntegerField(verbose_name="قیمت (تومان)")),
                (
                    "discount_price",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="برای محصول بدون تخفیف خالی بگذارید.",
                        null=True,
                        verbose_name="قیمت پس از تخفیف (تومان)",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(default=0, verbose_name="موجودی انبار"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="نمایش در سایت"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="پیشنهاد ویژه"),
                ),
                (
                    "sold_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد فروش"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.brand",
                        verbose_name="برند",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="تصویر مربعی پیشنهاد می\u200cشود (مثلاً ۱۰۰۰×۱۰۰۰ پیکسل).",
                        upload_to="products/%Y/%m/",
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="متن جایگزین (سئو)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="تصویر با کمترین عدد، تصویر اصلی است.",
                        verbose_name="ترتیب",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر محصول",
                "verbose_name_plural": "تصاویر محصول",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="مثال: حجم، نوع پوست، کشور سازنده",
                        max_length=100,
                        verbose_name="ویژگی",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="مثال: ۵۰ میلی\u200cلیتر",
                        max_length=200,
                        verbose_name="مقدار",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="catalog.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشخصه",
                "verbose_name_plural": "مشخصات فنی",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "-created_at"],
                name="catalog_pro_is_acti_ed6a39_idx",
            ),
        ),
    ]
