# Generated by Django 5.2.17 on 2026-09-26 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gateway", models.CharField(max_length=20, verbose_name="درگاه")),
                ("amount", models.PositiveBigIntegerField(verbose_name="مبلغ (ریال)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "ایجاد شده"),
                            ("redirected", "هدایت به درگاه"),
                            ("paid", "موفق"),
                            ("failed", "ناموفق"),
                            ("canceled", "انصراف از پرداخت"),
                        ],
                        db_index=True,
                        default="initiated",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="شناسه تراکنش درگاه",
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="کد پیگیری بانکی"
                    ),
                ),
                (
                    "card_pan",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="شماره کارت"
                    ),
                ),
                (
                    "message",
                    models.CharField(blank=True, max_length=255, verbose_name="پیام"),
                ),
                (
                    "request_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="پاسخ درخواست"
                    ),
                ),
                (
                    "verify_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="پاسخ تایید"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین تغییر"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تایید"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
            ],
            options={
                "verbose_name": "تراکنش پرداخت",
                "verbose_name_plural": "تراکنش\u200cهای پرداخت",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("authority", ""), _negated=True),
                        fields=("gateway", "authority"),
                        name="payments_unique_gateway_authority",
                    )
                ],
            },
        ),
    ]
