# Generated by Django 5.2.17 on 2026-09-20 19:41

import apps.accounts.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="نام کاربری شما همین شماره است.",
                        max_length=11,
                        unique=True,
                        validators=[apps.accounts.validators.validate_iranian_phone],
                        verbose_name="شماره موبایل",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="نام و نام خانوادگی"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, verbose_name="دسترسی پنل مدیریت"
                    ),
                ),
                (
                    "phone_verified",
                    models.BooleanField(default=False, verbose_name="شماره تایید شده"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ عضویت"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=11, verbose_name="شماره موبایل"
                    ),
                ),
                ("code", models.CharField(max_length=8, verbose_name="کد")),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("login", "ورود / ثبت\u200cنام"),
                            ("change_phone", "تغییر شماره موبایل"),
                        ],
                        default="login",
                        max_length=20,
                        verbose_name="هدف",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="تعداد تلاش"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="مصرف شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ارسال"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="زمان انقضا")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "کد تایید",
                "verbose_name_plural": "کدهای تایید",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="تصویر پروفایل",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
                ),
                (
                    "province",
                    models.CharField(blank=True, max_length=60, verbose_name="استان"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=60, verbose_name="شهر"),
                ),
                ("address", models.TextField(blank=True, verbose_name="آدرس پستی")),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=10, verbose_name="کد پستی"),
                ),
                (
                    "newsletter",
                    models.BooleanField(
                        default=True, verbose_name="دریافت پیامک تخفیف\u200cها"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "پروفایل",
                "verbose_name_plural": "پروفایل\u200cها",
            },
        ),
    ]
