# Generated by Django 5.2.17 on 2026-09-23 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SalonProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="آرایشگاه زنانه",
                        max_length=150,
                        verbose_name="نام مغازه",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="شعار کوتاه"
                    ),
                ),
                ("about", models.TextField(blank=True, verbose_name="درباره ما")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="salon/", verbose_name="لوگو"
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="salon/",
                        verbose_name="تصویر هدر سایت",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="آدرس مغازه")),
                (
                    "map_lat",
                    models.FloatField(
                        blank=True, null=True, verbose_name="عرض جغرافیایی (lat)"
                    ),
                ),
                (
                    "map_lng",
                    models.FloatField(
                        blank=True, null=True, verbose_name="طول جغرافیایی (lng)"
                    ),
                ),
                (
                    "map_link",
                    models.URLField(
                        blank=True,
                        help_text="اگر مختصات دقیق را ندارید، لینک اشتراک\u200cگذاری گوگل\u200cمپ را اینجا وارد کنید.",
                        verbose_name="لینک نقشه (اختیاری)",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="برای دکمه تماس در سایت",
                        max_length=15,
                        verbose_name="شماره تماس نمایشی",
                    ),
                ),
                (
                    "telegram_url",
                    models.URLField(blank=True, verbose_name="لینک تلگرام"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="لینک اینستاگرام"),
                ),
                (
                    "whatsapp_url",
                    models.URLField(
                        blank=True,
                        help_text="مثلاً https://wa.me/98912xxxxxxx",
                        verbose_name="لینک واتساپ",
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, verbose_name="لینک توییتر (X)"),
                ),
                (
                    "is_open_saturday",
                    models.BooleanField(default=True, verbose_name="باز - شنبه"),
                ),
                (
                    "is_open_sunday",
                    models.BooleanField(default=True, verbose_name="باز - یکشنبه"),
                ),
                (
                    "is_open_monday",
                    models.BooleanField(default=True, verbose_name="باز - دوشنبه"),
                ),
                (
                    "is_open_tuesday",
                    models.BooleanField(
                        default=True, verbose_name="باز - سه\u200cشنبه"
                    ),
                ),
                (
                    "is_open_wednesday",
                    models.BooleanField(default=True, verbose_name="باز - چهارشنبه"),
                ),
                (
                    "is_open_thursday",
                    models.BooleanField(default=True, verbose_name="باز - پنجشنبه"),
                ),
                (
                    "is_open_friday",
                    models.BooleanField(default=False, verbose_name="باز - جمعه"),
                ),
                (
                    "opening_time",
                    models.TimeField(
                        default=datetime.time(10, 0), verbose_name="ساعت باز شدن"
                    ),
                ),
                (
                    "closing_time",
                    models.TimeField(
                        default=datetime.time(20, 0), verbose_name="ساعت بسته شدن"
                    ),
                ),
                (
                    "slot_duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="فاصله بین نوبت\u200cها (دقیقه)"
                    ),
                ),
            ],
            options={
                "verbose_name": "اطلاعات مغازه",
                "verbose_name_plural": "اطلاعات مغازه",
            },
        ),
    ]
