# Generated by Django 5.2.17 on 2026-09-23 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=150, verbose_name="عنوان نمونه\u200cکار"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="نمایش در سایت"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "نمونه\u200cکار",
                "verbose_name_plural": "نمونه\u200cکارها",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="portfolio/", verbose_name="تصویر"),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("before", "قبل از انجام کار"),
                            ("after", "بعد از انجام کار"),
                            ("general", "عمومی"),
                        ],
                        default="general",
                        max_length=10,
                        verbose_name="نوع تصویر",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "portfolio_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="gallery.portfolioitem",
                        verbose_name="نمونه\u200cکار",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر نمونه\u200cکار",
                "verbose_name_plural": "تصاویر نمونه\u200cکار",
                "ordering": ["order", "id"],
            },
        ),
    ]
