# Generated by Django 5.2.17 on 2026-09-22 23:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="نام")),
                ("phone", models.CharField(max_length=20, verbose_name="شماره تماس")),
                (
                    "subject",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="موضوع"
                    ),
                ),
                ("message", models.TextField(verbose_name="متن پیام")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="خوانده شده"),
                ),
            ],
            options={
                "verbose_name": "پیام تماس",
                "verbose_name_plural": "پیام\u200cهای تماس",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        default="صافکاری و نقاشی",
                        max_length=120,
                        verbose_name="نام مغازه",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="صافکاری بدون رنگ، نقاشی و پولیش تخصصی",
                        max_length=200,
                        verbose_name="شعار کوتاه",
                    ),
                ),
                (
                    "about",
                    models.TextField(blank=True, verbose_name="درباره\u200cی ما"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="site/", verbose_name="لوگو"
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site/",
                        verbose_name="تصویر اصلی صفحه نخست",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="شماره تماس اصلی",
                    ),
                ),
                (
                    "second_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="شماره تماس دوم",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="ایمیل"
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(
                        blank=True,
                        default="شنبه تا پنجشنبه، ۹ صبح تا ۸ شب",
                        max_length=200,
                        verbose_name="ساعت کاری (متن نمایشی)",
                    ),
                ),
                (
                    "deposit_amount",
                    models.PositiveIntegerField(
                        default=200000,
                        help_text="مبلغی که هنگام رزرو نوبت به عنوان بیعانه از مشتری گرفته می\u200cشود.",
                        verbose_name="مبلغ پیش\u200cفرض بیعانه (تومان)",
                    ),
                ),
                (
                    "online_payment_enabled",
                    models.BooleanField(
                        default=True, verbose_name="پرداخت آنلاین بیعانه فعال باشد"
                    ),
                ),
                (
                    "require_deposit",
                    models.BooleanField(
                        default=False,
                        verbose_name="پرداخت بیعانه برای قطعی\u200cشدن نوبت الزامی است",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="توضیح متا (سئو)",
                    ),
                ),
                (
                    "enamad_code",
                    models.TextField(
                        blank=True, default="", verbose_name="کد نماد اعتماد الکترونیکی"
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات سایت",
                "verbose_name_plural": "تنظیمات سایت",
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("telegram", "تلگرام"),
                            ("instagram", "اینستاگرام"),
                            ("whatsapp", "واتساپ"),
                            ("twitter", "توییتر (X)"),
                            ("phone", "تماس تلفنی"),
                            ("eitaa", "ایتا"),
                            ("rubika", "روبیکا"),
                            ("aparat", "آپارات"),
                            ("youtube", "یوتیوب"),
                            ("linkedin", "لینکدین"),
                            ("email", "ایمیل"),
                            ("website", "وب\u200cسایت"),
                        ],
                        max_length=20,
                        verbose_name="شبکه اجتماعی",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="برای تلگرام/اینستاگرام آیدی بدون @، برای واتساپ و تماس شماره موبایل، برای بقیه نشانی کامل.",
                        max_length=255,
                        verbose_name="شناسه یا نشانی",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=80,
                        verbose_name="برچسب نمایشی",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="ترتیب نمایش"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "show_in_header",
                    models.BooleanField(
                        default=False, verbose_name="نمایش در بالای سایت"
                    ),
                ),
            ],
            options={
                "verbose_name": "لینک شبکه اجتماعی",
                "verbose_name_plural": "لینک\u200cهای شبکه اجتماعی",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="ShopLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                (
                    "title",
                    models.CharField(
                        default="شعبه اصلی", max_length=120, verbose_name="عنوان شعبه"
                    ),
                ),
                ("address", models.TextField(verbose_name="آدرس")),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="شهر"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="استان"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, default="", max_length=15, verbose_name="کد پستی"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="تلفن شعبه"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="مثال: ۳۵.۶۸۹۲ — از گوگل\u200cمپ یا نشان کپی کنید.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="عرض جغرافیایی",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="مثال: ۵۱.۳۸۹۰",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="طول جغرافیایی",
                    ),
                ),
                (
                    "map_zoom",
                    models.PositiveSmallIntegerField(
                        default=16, verbose_name="بزرگ\u200cنمایی نقشه"
                    ),
                ),
                (
                    "map_link",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="در صورت خالی بودن، لینک گوگل\u200cمپ از مختصات ساخته می\u200cشود.",
                        verbose_name="لینک مسیریابی",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(default=True, verbose_name="شعبه اصلی"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="نمایش در سایت"),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="core.sitesettings",
                        verbose_name="تنظیمات سایت",
                    ),
                ),
            ],
            options={
                "verbose_name": "لوکیشن مغازه",
                "verbose_name_plural": "لوکیشن مغازه",
                "ordering": ("-is_main", "title"),
            },
        ),
    ]
