# Generated by Django 5.2.17 on 2026-09-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="نام خدمت")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=170,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="توضیح کوتاه"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیحات کامل"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="services/",
                        verbose_name="تصویر خدمت",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(default=0, verbose_name="قیمت (تومان)"),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="مدت زمان (دقیقه)"
                    ),
                ),
                (
                    "deposit_amount",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="اگر صفر باشد، برای رزرو این خدمت بیعانه دریافت نمی\u200cشود.",
                        verbose_name="مبلغ بیعانه (تومان)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="فعال / نمایش در سایت"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "خدمت",
                "verbose_name_plural": "خدمات",
                "ordering": ["order", "name"],
            },
        ),
    ]
