# Generated by Django 5.2.17 on 2026-09-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=150, verbose_name="عنوان"),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="زیرعنوان"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="banners/", verbose_name="تصویر"),
                ),
                (
                    "link",
                    models.CharField(blank=True, max_length=300, verbose_name="لینک"),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="متن دکمه"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="ترتیب نمایش"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "بنر",
                "verbose_name_plural": "بنرها",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="بوتیک ایرانی",
                        max_length=120,
                        verbose_name="نام فروشگاه",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="شعار فروشگاه"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="site/", verbose_name="لوگو"
                    ),
                ),
                ("about", models.TextField(blank=True, verbose_name="درباره ما")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="شماره تماس"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="آدرس مغازه"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=80, verbose_name="شهر"),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=20, verbose_name="کد پستی"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="عرض جغرافیایی",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="طول جغرافیایی",
                    ),
                ),
                (
                    "map_embed_url",
                    models.URLField(
                        blank=True,
                        help_text="در صورت خالی بودن، از مختصات جغرافیایی نقشه ساخته می\u200cشود.",
                        verbose_name="لینک نقشه (iframe)",
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="ساعات کاری"
                    ),
                ),
                ("telegram", models.URLField(blank=True, verbose_name="تلگرام")),
                ("instagram", models.URLField(blank=True, verbose_name="اینستاگرام")),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="شماره با کد کشور، مثال: 989121234567",
                        max_length=120,
                        verbose_name="واتساپ",
                    ),
                ),
                ("twitter", models.URLField(blank=True, verbose_name="توییتر (X)")),
                (
                    "shipping_cost",
                    models.PositiveIntegerField(
                        default=0, verbose_name="هزینه ارسال (تومان)"
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="صفر یعنی غیرفعال",
                        verbose_name="سقف ارسال رایگان (تومان)",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات سایت",
                "verbose_name_plural": "تنظیمات سایت",
            },
        ),
    ]
