# Generated by Django 5.2.17 on 2026-09-20 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        default="dummy", max_length=30, verbose_name="درگاه"
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="مبلغ (تومان)")),
                (
                    "authority",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=120,
                        verbose_name="شناسه تراکنش درگاه",
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="کد رهگیری بانک"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "ایجاد شده"),
                            ("redirected", "هدایت به درگاه"),
                            ("success", "موفق"),
                            ("failed", "ناموفق"),
                            ("canceled", "لغو توسط کاربر"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="پیام خطا"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تایید"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت",
                "verbose_name_plural": "پرداخت\u200cها",
                "ordering": ["-created_at"],
            },
        ),
    ]
