# Generated by Django 5.2.17 on 2026-09-26 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="شماره سفارش",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پرداخت"),
                            ("paid", "پرداخت شده"),
                            ("processing", "در حال آماده\u200cسازی"),
                            ("shipped", "ارسال شده"),
                            ("delivered", "تحویل داده شده"),
                            ("canceled", "لغو شده"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(max_length=120, verbose_name="نام گیرنده"),
                ),
                (
                    "recipient_phone",
                    models.CharField(max_length=11, verbose_name="موبایل گیرنده"),
                ),
                ("province", models.CharField(max_length=40, verbose_name="استان")),
                ("city", models.CharField(max_length=60, verbose_name="شهر")),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="کد پستی"),
                ),
                ("address", models.TextField(verbose_name="نشانی")),
                ("note", models.TextField(blank=True, verbose_name="توضیحات مشتری")),
                (
                    "subtotal",
                    models.PositiveBigIntegerField(verbose_name="جمع کالاها (تومان)"),
                ),
                (
                    "shipping_cost",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="هزینه ارسال (تومان)"
                    ),
                ),
                (
                    "total",
                    models.PositiveBigIntegerField(
                        verbose_name="مبلغ قابل پرداخت (تومان)"
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="کد رهگیری مرسوله"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین تغییر"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پرداخت"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مشتری",
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارش\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="نام محصول"),
                ),
                (
                    "product_sku",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="کد محصول"
                    ),
                ),
                (
                    "unit_price",
                    models.PositiveBigIntegerField(verbose_name="قیمت واحد (تومان)"),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="تعداد")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="catalog.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "قلم سفارش",
                "verbose_name_plural": "اقلام سفارش",
            },
        ),
    ]
