# Generated by Django 5.2.17 on 2026-09-22 23:59

import accounts.models
import core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        error_messages={
                            "unique": "کاربری با این شماره موبایل قبلاً ثبت\u200cنام کرده است."
                        },
                        help_text="نام کاربری شما همین شماره موبایل است.",
                        max_length=11,
                        unique=True,
                        validators=[core.validators.validate_iran_mobile],
                        verbose_name="شماره موبایل",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="نام و نام خانوادگی",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="ایمیل"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/%Y/%m/",
                        verbose_name="تصویر پروفایل",
                    ),
                ),
                (
                    "car_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="مثال: پژو ۲۰۶ تیپ ۵ سفید",
                        max_length=120,
                        verbose_name="خودروی من",
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="شماره پلاک"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="برای کارفرما و کارکنان مغازه فعال شود.",
                        verbose_name="دسترسی به پنل مدیریت",
                    ),
                ),
                (
                    "is_phone_verified",
                    models.BooleanField(default=False, verbose_name="شماره تایید شده"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ عضویت"
                    ),
                ),
                (
                    "phone_changed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین تغییر شماره"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
                "ordering": ("-date_joined",),
            },
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=11, verbose_name="شماره موبایل"
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("login", "ورود یا ثبت\u200cنام"),
                            ("phone_change", "تغییر شماره موبایل"),
                        ],
                        default="login",
                        max_length=20,
                        verbose_name="کاربرد",
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(max_length=128, verbose_name="کد (هش\u200cشده)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ارسال"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="زمان انقضا")),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان استفاده"
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="تعداد تلاش ناموفق"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="آی\u200cپی درخواست"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "کد تایید پیامکی",
                "verbose_name_plural": "کدهای تایید پیامکی",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["phone", "purpose", "-created_at"],
                        name="accounts_ot_phone_b1f230_idx",
                    )
                ],
            },
        ),
    ]
