# Generated by Django 5.2.17 on 2026-09-29 10:40

import apps.core.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=120,
                        unique=True,
                        verbose_name="نامک (آدرس)",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
            ],
            options={
                "verbose_name": "دسته\u200cبندی مقاله",
                "verbose_name_plural": "دسته\u200cبندی مقالات",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=220,
                        unique=True,
                        verbose_name="نامک (آدرس)",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        help_text="ابعاد پیشنهادی: ۱۲۰۰×۶۷۵ پیکسل (۱۶ به ۹)",
                        upload_to="articles/%Y/%m/",
                        verbose_name="تصویر شاخص",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="در فهرست مقالات و نتایج گوگل نمایش داده می\u200cشود.",
                        max_length=500,
                        verbose_name="خلاصه",
                    ),
                ),
                ("body", apps.core.fields.RichTextField(verbose_name="متن مقاله")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "پیش\u200cنویس"), ("published", "منتشرشده")],
                        db_index=True,
                        default="draft",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="مقاله ویژه"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="برای انتشار زمان\u200cبندی\u200cشده، زمانی در آینده انتخاب کنید.",
                        verbose_name="زمان انتشار",
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد بازدید"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
                (
                    "related_products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="articles",
                        to="catalog.product",
                        verbose_name="محصولات مرتبط",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="blog.articlecategory",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقالات",
                "ordering": ["-published_at"],
            },
        ),
    ]
