# Generated by Django 5.2.17 on 2026-09-26 00:11

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="نام برند"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="نام لاتین"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=90,
                        unique=True,
                        verbose_name="نامک (آدرس)",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        upload_to=catalog.models.brand_logo_path,
                        verbose_name="لوگو",
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=60, verbose_name="کشور"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="درباره برند"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="ترتیب نمایش"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "برند",
                "verbose_name_plural": "برندها",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="نام")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, max_length=90, verbose_name="نامک (آدرس)"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("men", "مردانه"),
                            ("women", "زنانه"),
                            ("unisex", "یونیسکس (مشترک)"),
                            ("kids", "بچگانه"),
                        ],
                        help_text="برای زیردسته\u200cها مشخص کنید تا فیلتر «مردانه / زنانه» در کل فروشگاه کار کند.",
                        max_length=10,
                        verbose_name="جنسیت",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, max_length=140, verbose_name="شعار کوتاه"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=catalog.models.category_image_path,
                        verbose_name="تصویر",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="ترتیب نمایش"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="برای ساخت نوع ساعت (مثل اسپرت) خالی بگذارید؛ برای زنانه/مردانه، نوع ساعت را انتخاب کنید.",
                        limit_choices_to={"parent__isnull": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="catalog.category",
                        verbose_name="دسته والد (نوع ساعت)",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="نام محصول")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="نام یا مدل لاتین"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=180,
                        unique=True,
                        verbose_name="نامک (آدرس)",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="کد محصول",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=260, verbose_name="توضیح کوتاه"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیحات کامل"),
                ),
                ("price", models.PositiveBigIntegerField(verbose_name="قیمت (تومان)")),
                (
                    "compare_at_price",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="برای نمایش تخفیف پر کنید.",
                        null=True,
                        verbose_name="قیمت قبل از تخفیف (تومان)",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(default=1, verbose_name="موجودی انبار"),
                ),
                (
                    "movement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("quartz", "کوارتز (باتری)"),
                            ("automatic", "اتوماتیک"),
                            ("mechanical", "مکانیکی (کوکی)"),
                            ("solar", "خورشیدی"),
                            ("smart", "هوشمند"),
                        ],
                        max_length=20,
                        verbose_name="نوع موتور",
                    ),
                ),
                (
                    "strap_material",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("steel", "استیل"),
                            ("gold", "فلزی طلایی / رزگلد"),
                            ("leather", "چرم طبیعی"),
                            ("rubber", "رابر (سیلیکونی)"),
                            ("ceramic", "سرامیک"),
                            ("mesh", "حصیری (میلانیز)"),
                            ("fabric", "پارچه\u200cای"),
                        ],
                        max_length=20,
                        verbose_name="جنس بند",
                    ),
                ),
                (
                    "case_material",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="جنس بدنه"
                    ),
                ),
                (
                    "case_diameter",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="قطر بدنه (میلی\u200cمتر)",
                    ),
                ),
                (
                    "water_resistance",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="مقاومت در برابر آب (متر)"
                    ),
                ),
                (
                    "glass",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sapphire", "سافایر (یاقوت کبود)"),
                            ("mineral", "مینرال"),
                            ("hardlex", "هاردلکس"),
                            ("acrylic", "اکریلیک"),
                        ],
                        max_length=20,
                        verbose_name="جنس شیشه",
                    ),
                ),
                (
                    "warranty",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="گارانتی"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="نمایش در فروشگاه"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="محصول ویژه صفحه اصلی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.brand",
                        verbose_name="برند",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="زیرشاخه نهایی را انتخاب کنید؛ مثلاً «اسپرت › زنانه».",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=catalog.models.product_image_path,
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="متن جایگزین (alt)"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر محصول",
                "verbose_name_plural": "تصاویر محصول",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=80, verbose_name="عنوان ویژگی")),
                ("value", models.CharField(max_length=200, verbose_name="مقدار")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویژگی",
                "verbose_name_plural": "سایر ویژگی\u200cها",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("slug",),
                name="catalog_category_unique_root_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("parent", "slug"), name="catalog_category_unique_child_slug"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "-created_at"],
                name="catalog_pro_is_acti_ed6a39_idx",
            ),
        ),
    ]
