# Generated by Django 5.2.17 on 2026-09-29 10:40

import apps.core.fields
import apps.core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="به عنوان متن جایگزین تصویر هم استفاده می\u200cشود.",
                        max_length=150,
                        verbose_name="عنوان",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="زیرعنوان"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="اسلایدر: ۱۹۲۰×۶۴۰ پیکسل (نسبت ۳ به ۱) — بنر میانی: ۹۰۰×۴۰۰ پیکسل",
                        upload_to="banners/%Y/%m/",
                        verbose_name="تصویر دسکتاپ",
                    ),
                ),
                (
                    "mobile_image",
                    models.ImageField(
                        blank=True,
                        help_text="اختیاری؛ برای نمایش بهتر در موبایل — ۸۰۰×۶۰۰ پیکسل (نسبت ۴ به ۳)",
                        upload_to="banners/%Y/%m/",
                        verbose_name="تصویر موبایل",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="مثال: /products/?discount=1 یا /brands/نام-برند/ یا https://…",
                        max_length=300,
                        validators=[apps.core.models.validate_site_link],
                        verbose_name="لینک",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True,
                        help_text="مثال: مشاهده و خرید",
                        max_length=40,
                        verbose_name="متن دکمه",
                    ),
                ),
                (
                    "show_text",
                    models.BooleanField(
                        default=True, verbose_name="نمایش عنوان روی تصویر"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("hero", "اسلایدر اصلی صفحه نخست"),
                            ("promo", "بنر تبلیغاتی میانه صفحه نخست"),
                        ],
                        default="hero",
                        max_length=10,
                        verbose_name="محل نمایش",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="شروع نمایش"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایان نمایش"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "بنر",
                "verbose_name_plural": "بنرها و اسلایدر",
                "ordering": ["position", "order", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="فروشگاه مرکزی", max_length=120, verbose_name="نام شعبه"
                    ),
                ),
                ("address", models.TextField(verbose_name="آدرس")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="تلفن"),
                ),
                (
                    "working_hours",
                    models.CharField(
                        blank=True,
                        help_text="مثال: شنبه تا پنجشنبه ۱۰ تا ۲۱",
                        max_length=150,
                        verbose_name="ساعات کاری",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="با کلیک روی نقشه بالا به\u200cصورت خودکار پر می\u200cشود.",
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="عرض جغرافیایی (Latitude)",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="طول جغرافیایی (Longitude)",
                    ),
                ),
                (
                    "zoom",
                    models.PositiveSmallIntegerField(
                        default=16,
                        validators=[
                            django.core.validators.MinValueValidator(3),
                            django.core.validators.MaxValueValidator(19),
                        ],
                        verbose_name="بزرگنمایی نقشه",
                    ),
                ),
                (
                    "neshan_url",
                    models.URLField(
                        blank=True,
                        help_text="اختیاری؛ لینک اشتراک\u200cگذاری از اپلیکیشن نشان",
                        verbose_name="لینک مکان در نشان",
                    ),
                ),
                (
                    "balad_url",
                    models.URLField(
                        blank=True,
                        help_text="اختیاری؛ لینک اشتراک\u200cگذاری از اپلیکیشن بلد",
                        verbose_name="لینک مکان در بلد",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
            ],
            options={
                "verbose_name": "موقعیت فروشگاه",
                "verbose_name_plural": "موقعیت فروشگاه و شعب",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=160,
                        unique=True,
                        verbose_name="نامک (آدرس)",
                    ),
                ),
                (
                    "body",
                    apps.core.fields.RichTextField(blank=True, verbose_name="متن صفحه"),
                ),
                (
                    "show_in_footer",
                    models.BooleanField(default=True, verbose_name="نمایش در فوتر"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "صفحه",
                "verbose_name_plural": "صفحات ثابت (درباره ما، قوانین و …)",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="فروشگاه لوازم آرایشی",
                        max_length=100,
                        verbose_name="نام فروشگاه",
                    ),
                ),
                (
                    "slogan",
                    models.CharField(blank=True, max_length=200, verbose_name="شعار"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="site/", verbose_name="لوگو"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="تصویر مربعی، حداقل ۱۹۲×۱۹۲ پیکسل",
                        upload_to="site/",
                        verbose_name="آیکون سایت (favicon)",
                    ),
                ),
                (
                    "about_short",
                    models.TextField(
                        blank=True, verbose_name="معرفی کوتاه (نمایش در فوتر)"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="تلفن پشتیبانی"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                (
                    "working_hours",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="ساعات پاسخگویی"
                    ),
                ),
                (
                    "shipping_cost",
                    models.PositiveIntegerField(
                        default=50000, verbose_name="هزینه ارسال (تومان)"
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="عدد صفر یعنی ارسال رایگان غیرفعال است.",
                        verbose_name="حداقل خرید برای ارسال رایگان (تومان)",
                    ),
                ),
                (
                    "enamad_code",
                    models.TextField(
                        blank=True,
                        help_text="کد HTML دریافتی از سایت enamad.ir را اینجا قرار دهید تا در فوتر نمایش داده شود.",
                        verbose_name="کد نماد اعتماد الکترونیکی (اینماد)",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="توضیحات متا (سئو)"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "تنظیمات کلی سایت",
                "verbose_name_plural": "تنظیمات کلی سایت",
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "اینستاگرام"),
                            ("telegram", "تلگرام"),
                            ("whatsapp", "واتساپ"),
                            ("twitter", "توییتر (ایکس)"),
                            ("phone", "تلفن تماس"),
                            ("email", "ایمیل"),
                            ("eitaa", "ایتا"),
                            ("bale", "بله"),
                            ("rubika", "روبیکا"),
                            ("aparat", "آپارات"),
                            ("youtube", "یوتیوب"),
                        ],
                        max_length=20,
                        verbose_name="شبکه اجتماعی",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="اینستاگرام، تلگرام، توییتر و …: نام کاربری (مثل rozbeauty) یا لینک کامل. واتساپ و تلفن: شماره (مثل 09121234567 یا 02188776655). ایمیل: آدرس ایمیل.",
                        max_length=200,
                        verbose_name="نام کاربری / شماره / لینک",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="اختیاری؛ مثلاً «پشتیبانی واتساپ»",
                        max_length=60,
                        verbose_name="عنوان نمایشی",
                    ),
                ),
                (
                    "show_in_floating",
                    models.BooleanField(
                        default=True, verbose_name="نمایش در دکمه تماس شناور"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "لینک شبکه اجتماعی / تماس",
                "verbose_name_plural": "شبکه\u200cهای اجتماعی و راه\u200cهای تماس",
                "ordering": ["order", "id"],
            },
        ),
    ]
