# Generated by Django 5.2.17 on 2026-09-20 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="نام برند"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=140,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="brands/", verbose_name="لوگو"
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=80, verbose_name="کشور"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "برند",
                "verbose_name_plural": "برندها",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=60, unique=True, verbose_name="نام رنگ"
                    ),
                ),
                (
                    "hex_code",
                    models.CharField(
                        default="#000000",
                        help_text="مثال: #1f2937",
                        max_length=7,
                        verbose_name="کد رنگ",
                    ),
                ),
            ],
            options={
                "verbose_name": "رنگ",
                "verbose_name_plural": "رنگ\u200cها",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="نام دسته")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=160,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("women", "زنانه"),
                            ("men", "مردانه"),
                            ("unisex", "مشترک"),
                        ],
                        default="women",
                        max_length=10,
                        verbose_name="جنسیت",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.category",
                        verbose_name="دسته والد",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
                "ordering": ["gender", "order", "name"],
                "unique_together": {("name", "gender", "parent")},
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="نام محصول")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=220,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("clothing", "لباس"),
                            ("shoes", "کفش"),
                            ("bag", "کیف"),
                            ("accessory", "اکسسوری"),
                        ],
                        default="clothing",
                        max_length=20,
                        verbose_name="نوع کالا",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("women", "زنانه"),
                            ("men", "مردانه"),
                            ("unisex", "مشترک"),
                        ],
                        default="women",
                        max_length=10,
                        verbose_name="جنسیت",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="توضیح کوتاه"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("price", models.PositiveIntegerField(verbose_name="قیمت (تومان)")),
                (
                    "discount_price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="قیمت با تخفیف (تومان)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="محصول ویژه"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.brand",
                        verbose_name="برند",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="products/", verbose_name="تصویر"),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="متن جایگزین"
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="تصویر اصلی"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر محصول",
                "verbose_name_plural": "تصاویر محصول",
                "ordering": ["-is_main", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=30, verbose_name="سایز")),
                (
                    "size_type",
                    models.CharField(
                        choices=[
                            ("clothing", "لباس"),
                            ("shoes", "کفش"),
                            ("bag", "کیف"),
                            ("accessory", "اکسسوری"),
                        ],
                        default="clothing",
                        max_length=20,
                        verbose_name="نوع سایزبندی",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
            ],
            options={
                "verbose_name": "سایز",
                "verbose_name_plural": "سایزها",
                "ordering": ["size_type", "order", "label"],
                "unique_together": {("label", "size_type")},
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="کد انبار"
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(default=0, verbose_name="موجودی"),
                ),
                (
                    "extra_price",
                    models.IntegerField(default=0, verbose_name="اختلاف قیمت (تومان)"),
                ),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variants",
                        to="catalog.color",
                        verbose_name="رنگ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                        verbose_name="محصول",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variants",
                        to="catalog.size",
                        verbose_name="سایز",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنوع محصول",
                "verbose_name_plural": "تنوع\u200cهای محصول",
                "ordering": ["size__order", "color__name"],
                "unique_together": {("product", "size", "color")},
            },
        ),
    ]
