# Generated by Django 5.2.17 on 2026-09-26 00:11

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="عنوان")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=220, verbose_name="زیرعنوان"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="بنر هدر: حدود ۱۹۲۰×۱۶۰ پیکسل. بنر صفحه اصلی: حدود ۱۶۰۰×۹۰۰ پیکسل. بدون تصویر، بنر متنی با پس\u200cزمینه طلایی نمایش داده می\u200cشود.",
                        upload_to=core.models.banner_upload_path,
                        verbose_name="تصویر دسکتاپ",
                    ),
                ),
                (
                    "image_mobile",
                    models.ImageField(
                        blank=True,
                        help_text="اختیاری؛ حدود ۷۵۰×۲۰۰ برای بنر هدر.",
                        upload_to=core.models.banner_upload_path,
                        verbose_name="تصویر موبایل",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً /category/sport/ یا یک آدرس کامل",
                        max_length=300,
                        verbose_name="لینک",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="متن دکمه"
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("header", "بنر هدر (بالای همه صفحات)"),
                            ("home", "بنر تبلیغاتی صفحه اصلی"),
                        ],
                        default="header",
                        max_length=10,
                        verbose_name="محل نمایش",
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("gold", "طلایی"),
                            ("dark", "تیره"),
                            ("light", "روشن"),
                        ],
                        default="gold",
                        max_length=10,
                        verbose_name="سبک رنگی",
                    ),
                ),
                (
                    "show_text",
                    models.BooleanField(
                        default=True, verbose_name="نمایش متن روی تصویر"
                    ),
                ),
                (
                    "is_dismissible",
                    models.BooleanField(
                        default=True, verbose_name="کاربر بتواند بنر را ببندد"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="شروع نمایش"
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایان نمایش"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "بنر",
                "verbose_name_plural": "بنرها",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="نام")),
                ("phone", models.CharField(max_length=20, verbose_name="شماره تماس")),
                ("message", models.TextField(verbose_name="پیام")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="خوانده شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ارسال"),
                ),
            ],
            options={
                "verbose_name": "پیام تماس",
                "verbose_name_plural": "پیام\u200cهای تماس با ما",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=140,
                        unique=True,
                        verbose_name="نامک (آدرس)",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="می\u200cتوانید از تگ\u200cهای ساده HTML مثل <h2>، <p> و <ul> استفاده کنید.",
                        verbose_name="محتوا",
                    ),
                ),
                (
                    "show_in_footer",
                    models.BooleanField(default=True, verbose_name="نمایش در فوتر"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "صفحه",
                "verbose_name_plural": "صفحات ثابت",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="StoreLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="شعبه مرکزی", max_length=100, verbose_name="نام شعبه"
                    ),
                ),
                ("address", models.TextField(verbose_name="نشانی")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="تلفن شعبه"
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(
                        blank=True,
                        help_text="مثال: شنبه تا پنجشنبه ۱۰ الی ۲۲",
                        max_length=200,
                        verbose_name="ساعات کاری",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        verbose_name="عرض جغرافیایی (Latitude)",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        verbose_name="طول جغرافیایی (Longitude)",
                    ),
                ),
                (
                    "zoom",
                    models.PositiveSmallIntegerField(
                        default=16, verbose_name="بزرگنمایی نقشه"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=core.models.store_upload_path,
                        verbose_name="تصویر مغازه",
                    ),
                ),
                (
                    "neshan_url",
                    models.URLField(
                        blank=True,
                        help_text="اختیاری؛ در غیر این صورت خودکار ساخته می\u200cشود.",
                        verbose_name="لینک نشان",
                    ),
                ),
                (
                    "balad_url",
                    models.URLField(
                        blank=True,
                        help_text="اختیاری؛ در غیر این صورت خودکار ساخته می\u200cشود.",
                        verbose_name="لینک بلد",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
            ],
            options={
                "verbose_name": "لوکیشن مغازه",
                "verbose_name_plural": "لوکیشن مغازه\u200cها",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="ثانیه", max_length=80, verbose_name="نام فروشگاه"
                    ),
                ),
                (
                    "site_name_en",
                    models.CharField(
                        blank=True,
                        default="SANIYEH",
                        max_length=80,
                        verbose_name="نام لاتین",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="گالری ساعت\u200cهای اصل مردانه و زنانه",
                        max_length=160,
                        verbose_name="شعار",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="اگر خالی باشد، نام فروشگاه به\u200cصورت لوگوتایپ نمایش داده می\u200cشود.",
                        upload_to=core.models.site_upload_path,
                        verbose_name="لوگو",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="مثال: 021-12345678",
                        max_length=30,
                        verbose_name="شماره تماس",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="موبایل پشتیبانی"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                ("address", models.TextField(blank=True, verbose_name="نشانی (فوتر)")),
                (
                    "working_hours",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="ساعات پاسخگویی"
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True,
                        help_text="نام کاربری (بدون @) یا لینک کامل",
                        max_length=200,
                        verbose_name="تلگرام",
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True,
                        help_text="نام کاربری یا لینک کامل",
                        max_length=200,
                        verbose_name="اینستاگرام",
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="شماره موبایل (مثلاً 09121234567) یا لینک کامل",
                        max_length=200,
                        verbose_name="واتساپ",
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True,
                        help_text="نام کاربری یا لینک کامل",
                        max_length=200,
                        verbose_name="توییتر (ایکس)",
                    ),
                ),
                (
                    "eitaa",
                    models.CharField(blank=True, max_length=200, verbose_name="ایتا"),
                ),
                (
                    "bale",
                    models.CharField(blank=True, max_length=200, verbose_name="بله"),
                ),
                (
                    "rubika",
                    models.CharField(blank=True, max_length=200, verbose_name="روبیکا"),
                ),
                (
                    "enamad_code",
                    models.TextField(
                        blank=True,
                        help_text="کد HTML دریافتی از پنل enamad.ir را کامل و بدون تغییر اینجا قرار دهید.",
                        verbose_name="کد نماد اعتماد الکترونیکی (اینماد)",
                    ),
                ),
                (
                    "samandehi_code",
                    models.TextField(
                        blank=True,
                        help_text="اختیاری؛ کد HTML نشان ساماندهی.",
                        verbose_name="کد نشان ساماندهی",
                    ),
                ),
                (
                    "footer_about",
                    models.TextField(
                        blank=True, verbose_name="متن معرفی کوتاه در فوتر"
                    ),
                ),
                (
                    "copyright_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="متن کپی\u200cرایت"
                    ),
                ),
                (
                    "hero_eyebrow",
                    models.CharField(
                        blank=True,
                        default="گالری ساعت ثانیه",
                        max_length=80,
                        verbose_name="روتیتر",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="هر ثانیه، یک شاهکار",
                        max_length=120,
                        verbose_name="تیتر اصلی",
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        blank=True,
                        default="اصیل\u200cترین ساعت\u200cهای مچی مردانه و زنانه؛ با ضمانت اصالت، ارسال بیمه\u200cشده و مشاوره تخصصی.",
                        verbose_name="متن زیر تیتر",
                    ),
                ),
                (
                    "hero_cta_text",
                    models.CharField(
                        blank=True,
                        default="مشاهده مجموعه",
                        max_length=40,
                        verbose_name="متن دکمه",
                    ),
                ),
                (
                    "hero_cta_url",
                    models.CharField(
                        blank=True,
                        default="/shop/",
                        max_length=300,
                        verbose_name="لینک دکمه",
                    ),
                ),
                (
                    "hero_metal",
                    models.CharField(
                        choices=[
                            ("rose", "رزگلد"),
                            ("gold", "طلایی"),
                            ("steel", "استیل نقره\u200cای"),
                            ("black", "مشکی مات"),
                        ],
                        default="rose",
                        max_length=10,
                        verbose_name="رنگ بدنه ساعت سه\u200cبعدی",
                    ),
                ),
                (
                    "hero_dial",
                    models.CharField(
                        choices=[
                            ("chocolate", "شکلاتی سان\u200cبرست"),
                            ("black", "مشکی"),
                            ("blue", "سرمه\u200cای"),
                            ("green", "سبز زیتونی"),
                            ("silver", "نقره\u200cای"),
                            ("champagne", "شامپاینی"),
                        ],
                        default="chocolate",
                        max_length=10,
                        verbose_name="رنگ صفحه ساعت سه\u200cبعدی",
                    ),
                ),
                (
                    "shipping_cost",
                    models.PositiveIntegerField(
                        default=150000, verbose_name="هزینه ارسال (تومان)"
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.PositiveBigIntegerField(
                        default=10000000,
                        help_text="صفر یعنی ارسال رایگان غیرفعال است.",
                        verbose_name="ارسال رایگان برای خرید بالای (تومان)",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="توضیحات متا (سئو)"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hero_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.product",
                        verbose_name="محصول معرفی\u200cشده در انتهای انیمیشن",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات سایت",
                "verbose_name_plural": "تنظیمات سایت",
            },
        ),
    ]
