# Generated by Django 5.2.17 on 2026-09-23 22:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="شماره موبایل باید به\u200cصورت ۰۹xxxxxxxxx و ۱۱ رقم باشد.",
                                regex="^09\\d{9}$",
                            )
                        ],
                        verbose_name="شماره تماس",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="توضیحات مشتری")),
                ("date", models.DateField(verbose_name="تاریخ نوبت")),
                ("start_time", models.TimeField(verbose_name="ساعت شروع")),
                ("end_time", models.TimeField(verbose_name="ساعت پایان")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_deposit", "در انتظار پرداخت بیعانه"),
                            ("pending", "در انتظار بررسی و تایید"),
                            ("confirmed", "تایید شده"),
                            ("cancelled", "لغو شده"),
                            ("done", "انجام شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="یادداشت داخلی"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="services.service",
                        verbose_name="خدمت",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مشتری",
                    ),
                ),
            ],
            options={
                "verbose_name": "نوبت",
                "verbose_name_plural": "نوبت\u200cها",
                "ordering": ["date", "start_time"],
            },
        ),
    ]
