# Generated by Django 5.2.17 on 2026-09-22 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="نام دسته"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=120,
                        unique=True,
                        verbose_name="نشانی یکتا",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="توضیح"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="نام آیکون دلخواه برای نمایش کنار دسته.",
                        max_length=40,
                        verbose_name="آیکون",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "دسته خدمت",
                "verbose_name_plural": "دسته\u200cبندی خدمات",
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                ("title", models.CharField(max_length=150, verbose_name="عنوان خدمت")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=170,
                        unique=True,
                        verbose_name="نشانی یکتا",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=250,
                        verbose_name="توضیح کوتاه",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="توضیح کامل"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="services/%Y/%m/",
                        verbose_name="تصویر خدمت",
                    ),
                ),
                (
                    "base_price",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="عدد ۰ یعنی «قیمت پس از کارشناسی».",
                        verbose_name="قیمت پایه (تومان)",
                    ),
                ),
                (
                    "price_note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="مثال: از ۵۰۰ هزار تومان، بسته به میزان آسیب",
                        max_length=120,
                        verbose_name="توضیح قیمت",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=60,
                        help_text="برای محاسبه\u200cی نوبت\u200cهای خالی استفاده می\u200cشود.",
                        verbose_name="مدت زمان تقریبی (دقیقه)",
                    ),
                ),
                (
                    "deposit_amount",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="اگر ۰ باشد، مبلغ پیش\u200cفرض تنظیمات سایت استفاده می\u200cشود.",
                        verbose_name="بیعانه\u200cی این خدمت (تومان)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="فعال (نمایش در سایت)"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="نمایش در صفحه نخست"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="ترتیب نمایش"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services",
                        to="services.servicecategory",
                        verbose_name="دسته",
                    ),
                ),
            ],
            options={
                "verbose_name": "خدمت",
                "verbose_name_plural": "خدمات",
                "ordering": ("order", "title"),
                "indexes": [
                    models.Index(
                        fields=["is_active", "order"],
                        name="services_se_is_acti_dbc8d8_idx",
                    )
                ],
            },
        ),
    ]
