# Generated by Django 5.2.17 on 2026-09-22 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                ("title", models.CharField(max_length=150, verbose_name="عنوان")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, default="", max_length=250, verbose_name="زیرعنوان"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="banners/%Y/%m/", verbose_name="تصویر بنر"
                    ),
                ),
                (
                    "mobile_image",
                    models.ImageField(
                        blank=True,
                        help_text="اختیاری؛ اگر خالی باشد همان تصویر اصلی نمایش داده می\u200cشود.",
                        null=True,
                        upload_to="banners/%Y/%m/",
                        verbose_name="تصویر نسخه موبایل",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="لینک مقصد"
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True, default="", max_length=60, verbose_name="متن دکمه"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("hero", "اسلایدر بالای صفحه نخست"),
                            ("middle", "میانه\u200cی صفحه نخست"),
                            ("sidebar", "ستون کناری"),
                            ("footer", "پایین صفحه"),
                        ],
                        default="hero",
                        max_length=20,
                        verbose_name="محل نمایش",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="شروع نمایش"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایان نمایش"
                    ),
                ),
            ],
            options={
                "verbose_name": "بنر",
                "verbose_name_plural": "بنرها",
                "ordering": ("order", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=160, verbose_name="عنوان نمونه\u200cکار"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=180,
                        unique=True,
                        verbose_name="نشانی یکتا",
                    ),
                ),
                (
                    "car_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="مثال: پراید ۱۳۱ سفید",
                        max_length=120,
                        verbose_name="خودرو",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="شرح کار انجام\u200cشده"
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        help_text="اگر خالی باشد، اولین عکس «بعد» به عنوان کاور استفاده می\u200cشود.",
                        null=True,
                        upload_to="portfolio/%Y/%m/",
                        verbose_name="تصویر شاخص",
                    ),
                ),
                (
                    "duration_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="مثال: ۲ روز کاری",
                        max_length=80,
                        verbose_name="مدت انجام کار",
                    ),
                ),
                (
                    "completed_at",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ انجام"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="نمایش در صفحه نخست"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolio_items",
                        to="services.service",
                        verbose_name="خدمت مرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "نمونه\u200cکار",
                "verbose_name_plural": "نمونه\u200cکارها",
                "ordering": ("order", "-completed_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="PortfolioImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="portfolio/%Y/%m/", verbose_name="عکس"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("before", "قبل از انجام کار"),
                            ("during", "حین انجام کار"),
                            ("after", "بعد از انجام کار"),
                        ],
                        default="after",
                        max_length=10,
                        verbose_name="نوع عکس",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="توضیح عکس"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="gallery.portfolioitem",
                        verbose_name="نمونه\u200cکار",
                    ),
                ),
            ],
            options={
                "verbose_name": "عکس نمونه\u200cکار",
                "verbose_name_plural": "عکس\u200cهای نمونه\u200cکار",
                "ordering": ("kind", "order", "id"),
            },
        ),
    ]
