# Generated by Django 5.2.17 on 2026-09-29 10:40

import apps.accounts.fields
import apps.accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "phone",
                    apps.accounts.fields.PhoneNumberField(
                        error_messages={
                            "unique": "کاربری با این شماره موبایل قبلاً ثبت شده است."
                        },
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^09\\d{9}$",
                                "شماره موبایل باید ۱۱ رقم باشد و با ۰۹ شروع شود (مثال: 09123456789).",
                            )
                        ],
                        verbose_name="شماره موبایل",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=100, verbose_name="نام"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="نام خانوادگی"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        upload_to="avatars/%Y/%m/",
                        verbose_name="تصویر پروفایل",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="کاربر می\u200cتواند وارد پنل مدیریت شود.",
                        verbose_name="دسترسی به پنل مدیریت",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ عضویت"
                    ),
                ),
                (
                    "phone_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین تایید شماره موبایل"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً خانه یا محل کار",
                        max_length=50,
                        verbose_name="عنوان آدرس",
                    ),
                ),
                (
                    "receiver_name",
                    models.CharField(
                        max_length=120, verbose_name="نام و نام خانوادگی گیرنده"
                    ),
                ),
                (
                    "receiver_phone",
                    apps.accounts.fields.PhoneNumberField(
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^09\\d{9}$",
                                "شماره موبایل باید ۱۱ رقم باشد و با ۰۹ شروع شود (مثال: 09123456789).",
                            )
                        ],
                        verbose_name="موبایل گیرنده",
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("آذربایجان شرقی", "آذربایجان شرقی"),
                            ("آذربایجان غربی", "آذربایجان غربی"),
                            ("اردبیل", "اردبیل"),
                            ("اصفهان", "اصفهان"),
                            ("البرز", "البرز"),
                            ("ایلام", "ایلام"),
                            ("بوشهر", "بوشهر"),
                            ("تهران", "تهران"),
                            ("چهارمحال و بختیاری", "چهارمحال و بختیاری"),
                            ("خراسان جنوبی", "خراسان جنوبی"),
                            ("خراسان رضوی", "خراسان رضوی"),
                            ("خراسان شمالی", "خراسان شمالی"),
                            ("خوزستان", "خوزستان"),
                            ("زنجان", "زنجان"),
                            ("سمنان", "سمنان"),
                            ("سیستان و بلوچستان", "سیستان و بلوچستان"),
                            ("فارس", "فارس"),
                            ("قزوین", "قزوین"),
                            ("قم", "قم"),
                            ("کردستان", "کردستان"),
                            ("کرمان", "کرمان"),
                            ("کرمانشاه", "کرمانشاه"),
                            ("کهگیلویه و بویراحمد", "کهگیلویه و بویراحمد"),
                            ("گلستان", "گلستان"),
                            ("گیلان", "گیلان"),
                            ("لرستان", "لرستان"),
                            ("مازندران", "مازندران"),
                            ("مرکزی", "مرکزی"),
                            ("هرمزگان", "هرمزگان"),
                            ("همدان", "همدان"),
                            ("یزد", "یزد"),
                        ],
                        max_length=40,
                        verbose_name="استان",
                    ),
                ),
                ("city", models.CharField(max_length=60, verbose_name="شهر")),
                ("full_address", models.TextField(verbose_name="آدرس کامل پستی")),
                (
                    "postal_code",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10}$", "کد پستی باید ۱۰ رقم باشد."
                            )
                        ],
                        verbose_name="کد پستی",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="آدرس پیش\u200cفرض"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "آدرس",
                "verbose_name_plural": "آدرس\u200cها",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=11, verbose_name="شماره موبایل"
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("login", "ورود / ثبت\u200cنام"),
                            ("change_phone", "تغییر شماره موبایل"),
                        ],
                        max_length=20,
                        verbose_name="کاربرد",
                    ),
                ),
                ("code_hash", models.CharField(max_length=128)),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="تعداد تلاش ناموفق"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="استفاده/باطل شده"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, db_index=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="زمان ارسال"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="زمان انقضا")),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان استفاده"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "کد تایید پیامکی",
                "verbose_name_plural": "کدهای تایید پیامکی",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone", "purpose", "created_at"],
                        name="accounts_ot_phone_4a5cc3_idx",
                    )
                ],
            },
        ),
    ]
